### ISSUE TITLE
Does not work properly

### ISSUE THREAD

**Issue by gl4nce** [0xprime/NessusReportMerger#1]
Merging is working fine, but hosts are listed twice after merging two nessus files. The same host should not be listed twice.

**Comment by 0xprime** [comment]
Are you merging together two scans with overlapping IP ranges?

**Comment by gl4nce** [comment]
Exactly. I did two scans with the same ip-ranges but different settings. Now I wanted to merge them, but that did not work properly and all hosts are listed twice (with different findings in some cases).

**Comment by 0xprime** [comment]
I understand. 

The script is not designed to handle that, as the intention was to combine scans of multiple IP ranges into one scan for easier reporting/statistics. As far as the script is concerned, seeing the same IP address twice is considered as two different assets.

**Comment by gl4nce** [comment]
Then this should be stated on the readme and in my opinion it's just a bug.
